apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2025-03-26T15:05:00Z"
  generation: 1
  name: newpods
  namespace: default
  resourceVersion: "791"
  uid: a070d1ca-964b-4cb9-afee-3c23a72d71c6
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: busybox
  template:
    metadata:
      creationTimestamp: null
      labels:
        tier: busybox
    spec:
      containers:
      - command:
        - sleep
        - "1000"
        image: busybox
        imagePullPolicy: Always
        name: busybox
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  fullyLabeledReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3