apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2025-03-26T16:40:15Z"
    generation: 1
    name: frontend-deployment
    namespace: default
    resourceVersion: "855"
    uid: d2868ce1-a034-4d02-9b9e-8212e1d9121f
  spec:
    progressDeadlineSeconds: 600
    replicas: 4
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        name: busybox-pod
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: busybox-pod
      spec:
        containers:
        - command:
          - sh
          - -c
          - echo Hello Kubernetes! && sleep 3600
          image: busybox888
          imagePullPolicy: Always
          name: busybox-container
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2025-03-26T16:40:15Z"
      lastUpdateTime: "2025-03-26T16:40:15Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2025-03-26T16:40:15Z"
      lastUpdateTime: "2025-03-26T16:40:15Z"
      message: ReplicaSet "frontend-deployment-cd6b557c" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 1
    replicas: 4
    unavailableReplicas: 4
    updatedReplicas: 4
kind: List
metadata:
  resourceVersion: ""