apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-26T16:57:25Z"
  name: db-service
  namespace: marketing
  resourceVersion: "801"
  uid: dfcf832b-40c1-44d9-8ce1-a884ce4f5bd0
spec:
  clusterIP: 10.43.39.7
  clusterIPs:
  - 10.43.39.7
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32632
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}