apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-26T16:57:25Z"
  name: db-service
  namespace: dev
  resourceVersion: "805"
  uid: 40b4659d-18a6-427c-aa6d-ee3ca9d8d9de
spec:
  clusterIP: 10.43.231.9
  clusterIPs:
  - 10.43.231.9
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}