apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-03-26T16:57:25Z"
  name: red-service
  namespace: manufacturing
  resourceVersion: "791"
  uid: 192a8c37-e207-4ff8-b195-2727d89691f0
spec:
  clusterIP: 10.43.104.100
  clusterIPs:
  - 10.43.104.100
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: red-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}