apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-26T16:57:25Z"
  name: dna-1
  namespace: research
  resourceVersion: "1398"
  uid: bfeef1eb-71ca-456c-b379-d1bd4da8c722
spec:
  containers:
  - image: busybox
    imagePullPolicy: Always
    name: busybox
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bqm9k
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: controlplane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-bqm9k
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-03-26T16:57:28Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-03-26T16:57:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-03-26T17:13:28Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-03-26T17:13:28Z"
    message: 'containers with unready status: [busybox]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-03-26T16:57:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://11e7e296d70e3568c4aa45ebc91ed2c13a100f0c2357549b56a8bfc71d1ea6b0
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:37f7b378a29ceb4c551b1b5582e27747b855bbfaa73fa11914fe0df028dc581f
    lastState:
      terminated:
        containerID: containerd://11e7e296d70e3568c4aa45ebc91ed2c13a100f0c2357549b56a8bfc71d1ea6b0
        exitCode: 0
        finishedAt: "2025-03-26T17:18:34Z"
        reason: Completed
        startedAt: "2025-03-26T17:18:34Z"
    name: busybox
    ready: false
    restartCount: 9
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=busybox pod=dna-1_research(bfeef1eb-71ca-456c-b379-d1bd4da8c722)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bqm9k
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.183.200
  hostIPs:
  - ip: 192.168.183.200
  phase: Running
  podIP: 10.22.0.9
  podIPs:
  - ip: 10.22.0.9
  qosClass: BestEffort
  startTime: "2025-03-26T16:57:25Z"